# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestApp

pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage','~>4.0'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework/Swift'
  pod 'Alamofire'

  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestAppUITests' do
    # Pods for testing
  end

end
